# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genericListViewWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from latex_template import compile_pattern
from PyQt5.QtGui import QPixmap


class Ui_genericForm(object):
    def setupUi(self, genericForm):
        genericForm.setObjectName("genericForm")
        genericForm.resize(1748, 1359)

        # Section: verticalLayout_2
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(genericForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Section: splitter
        self.splitter = QtWidgets.QSplitter(genericForm)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # Section: layoutWidget
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")

        # Section: items_layout
        self.items_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.items_layout.setContentsMargins(0, 0, 0, 0)
        self.items_layout.setObjectName("items_layout")

        # Section: list_label
        self.list_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_label.setFont(font)
        self.list_label.setObjectName("list_label")
        self.items_layout.addWidget(self.list_label)

        # Section: filter_hLayout
        self.filter_hLayout = QtWidgets.QHBoxLayout()
        self.filter_hLayout.setObjectName("filter_hLayout")

        # Section: filter_label
        self.filter_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_label.setFont(font)
        self.filter_label.setObjectName("filter_label")
        self.filter_hLayout.addWidget(self.filter_label)

        # Section: filter_lineEdit
        self.filter_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.filter_lineEdit.setFont(font)
        self.filter_lineEdit.setObjectName("filter_lineEdit")
        self.filter_hLayout.addWidget(self.filter_lineEdit)
        self.items_layout.addLayout(self.filter_hLayout)

        # Section: listWidget
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.items_layout.addWidget(self.listWidget)

        # Section: addRemove_hLayout
        self.addRemove_hLayout = QtWidgets.QHBoxLayout()
        self.addRemove_hLayout.setObjectName("addRemove_hLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.addRemove_hLayout.addItem(spacerItem)

        # Section: remove_btn
        self.remove_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.addRemove_hLayout.addWidget(self.remove_btn)

        # Section: add_btn
        self.add_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.addRemove_hLayout.addWidget(self.add_btn)
        self.items_layout.addLayout(self.addRemove_hLayout)

        # Section: widget
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")

        # Section: verticalLayout
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Section: formLayout
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")

        # Section: name_label
        self.name_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)

        # Section: name_lineEdit
        self.name_lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)

        # Section: type_label
        self.type_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label.sizePolicy().hasHeightForWidth())
        self.type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type_label.setFont(font)
        self.type_label.setObjectName("type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.type_label)

        # Section: type_comboBox
        self.type_comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type_comboBox.setFont(font)
        self.type_comboBox.setObjectName("type_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.type_comboBox)
        self.verticalLayout.addLayout(self.formLayout)

        # Section: latex_label
        self.latex_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.latex_label.setFont(font)
        self.latex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.latex_label.setObjectName("latex_label")
        self.verticalLayout.addWidget(self.latex_label)

        # Section: textEdit
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        # Section: latexBtns_hLayout
        self.latexBtns_hLayout = QtWidgets.QHBoxLayout()
        self.latexBtns_hLayout.setObjectName("latexBtns_hLayout")

        # Section: latexTemplate_btn
        self.latexTemplate_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latexTemplate_btn.sizePolicy().hasHeightForWidth())
        self.latexTemplate_btn.setSizePolicy(sizePolicy)
        self.latexTemplate_btn.setMinimumSize(QtCore.QSize(0, 74))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.latexTemplate_btn.setFont(font)
        self.latexTemplate_btn.setObjectName("latexTemplate_btn")
        self.latexBtns_hLayout.addWidget(self.latexTemplate_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.latexBtns_hLayout.addItem(spacerItem1)

        # Section: generate_btn
        self.generate_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_btn.sizePolicy().hasHeightForWidth())
        self.generate_btn.setSizePolicy(sizePolicy)
        self.generate_btn.setMinimumSize(QtCore.QSize(0, 74))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.generate_btn.setFont(font)
        self.generate_btn.setObjectName("generate_btn")
        self.generate_btn.clicked.connect(self.compile_latex)
        self.latexBtns_hLayout.addWidget(self.generate_btn)
        self.verticalLayout.addLayout(self.latexBtns_hLayout)

        # Section: image_vLayout
        self.image_vLayout = QtWidgets.QVBoxLayout()
        self.image_vLayout.setObjectName("image_vLayout")

        # Section: image_label
        self.image_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.image_label.setFont(font)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.image_vLayout.addWidget(self.image_label)

        # Section: image_gView
        self.image_gView = QtWidgets.QGraphicsView(self.widget)
        self.image_gView.setMinimumSize(QtCore.QSize(907, 369))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.image_gView.setFont(font)
        self.image_gView.setObjectName("image_gView")
        self.image_vLayout.addWidget(self.image_gView)
        self.verticalLayout.addLayout(self.image_vLayout)

        # Section: update_hLayout
        self.update_hLayout = QtWidgets.QHBoxLayout()
        self.update_hLayout.setObjectName("update_hLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.update_hLayout.addItem(spacerItem2)

        # Section: update_btn
        self.update_btn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.update_btn.setFont(font)
        self.update_btn.setObjectName("update_btn")
        self.update_hLayout.addWidget(self.update_btn)

        self.verticalLayout.addLayout(self.update_hLayout)
        self.verticalLayout_2.addWidget(self.splitter)
        self.list_label.setBuddy(self.listWidget)
        self.filter_label.setBuddy(self.filter_lineEdit)
        self.name_label.setBuddy(self.name_lineEdit)
        self.type_label.setBuddy(self.type_comboBox)
        self.latex_label.setBuddy(self.textEdit)
        self.image_label.setBuddy(self.image_gView)

        self.retranslateUi(genericForm)
        QtCore.QMetaObject.connectSlotsByName(genericForm)

    def compile_latex(self):
        text = self.textEdit.toPlainText()
        png_data: bytes = compile_pattern(pattern=text)

        qp = QPixmap()
        qp.loadFromData(png_data)
        scene = QtWidgets.QGraphicsScene()
        self.image_gView.setScene(scene)
        scene.addPixmap(qp)

    def retranslateUi(self, genericForm):
        _translate = QtCore.QCoreApplication.translate
        genericForm.setWindowTitle(_translate("genericForm", "Form"))
        self.list_label.setText(_translate("genericForm", "TextLabel"))
        self.filter_label.setText(_translate("genericForm", "Filter"))
        self.remove_btn.setText(_translate("genericForm", "Remove"))
        self.add_btn.setText(_translate("genericForm", "Add"))
        self.name_label.setText(_translate("genericForm", "TextLabel"))
        self.type_label.setText(_translate("genericForm", "TextLabel"))
        self.latex_label.setText(_translate("genericForm", "LaTeX"))
        self.latexTemplate_btn.setText(_translate("genericForm", "LaTex Template"))
        self.generate_btn.setText(_translate("genericForm", "Generate"))
        self.image_label.setText(_translate("genericForm", "Image"))
        self.update_btn.setText(_translate("genericForm", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    genericForm = QtWidgets.QWidget()
    ui = Ui_genericForm()
    ui.setupUi(genericForm)
    genericForm.show()
    sys.exit(app.exec_())
